#!/usr/bin/env bash
# This script installs and configures Nginx web server on an Ubuntu machine

# Update the package list and install nginx
apt-get update -y
apt-get install nginx -y

# Make sure Nginx is listening on port 80
ufw allow 'Nginx HTTP'

# Start Nginx without using systemctl
service nginx start

# Check if Nginx is running
netstat -tuln | grep :80

# Modify the default web page to contain "Holberton School"
echo "Holberton School for the win!" > /var/www/html/index.html
