#!/usr/bin/env bash
# Updates the current state of the server
# Installs Nginx on the server
# Changes the user and user group ownership for editing files
# Overwrites the default page of Nginx
# Overwrites the default configuration file for Nginx
# Adds a redirection rule and a location for the redirection
# Restarts Nginx to apply changes

apt-get -y update
apt-get install -y nginx
sudo chown -R "$USER":"$USER" /var/www/html
sudo chown -R "$USER":"$USER" /etc/nginx/sites-available/default

echo "Holberton School for the win!" > /var/www/html/index.html

echo "server {
    listen 80 default_server;
    listen [::]:80 default_server;
    root /var/www/html;
    index index.html index.htm index.nginx-debian.html;
    server_name _;
    
    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=-VGIt10m9VQ;
    }
}" > /etc/nginx/sites-available/default

sudo chown -R root:root /var/www/html
sudo chown -R root:root /etc/nginx/sites-available/default

sudo service nginx restart
sudo service nginx reload
