#!/usr/bin/env bash
# Install nginx on your web-01 server
apt-get -y update
apt-get -y install nginx

# Set the content for the index page
echo "Hello World!" | sudo tee /var/www/html/index.html > /dev/null

# Set the rewrite rule for redirection
echo "rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;" | sudo tee -a /etc/nginx/sites-available/default > /dev/null

# Create the custom 404 page with the required string
echo "Ceci n'est pas une page" | sudo tee /var/www/html/custom_404.html > /dev/null

# Add the error page directive at the appropriate location
echo "error_page 404 /custom_404.html;" | sudo tee -a /etc/nginx/sites-available/default > /dev/null

# Restart nginx service to apply changes
service nginx restart
